# Generated by Django 3.0.5 on 2020-04-24 10:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company_Info',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company', models.TextField()),
                ('units', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Credit_Info',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bank', models.TextField()),
                ('credit', models.DecimalField(decimal_places=2, max_digits=15)),
                ('used', models.DecimalField(decimal_places=2, max_digits=15)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.Company_Info')),
            ],
        ),
    ]
