# Generated by Django 3.0.5 on 2020-05-05 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_auto_20200424_1809'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company_info',
            name='company',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='company_info',
            name='units',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='credit_info',
            name='bank',
            field=models.CharField(max_length=100),
        ),
    ]
